/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void Test(){
        System.out.println("This is Gradle project");

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Test();
    
    }
}

